config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :tasks

  map.resources :projects

  map.resources :invoices

  map.resources :hour_reports

  map.resources :expenses

  map.resources :project_costs

  map.resources :contacts

  map.resources :businesses

  

  
  map.resource :user_session
  map.root :controller => "dashboard", :action => "index" # optional, this just sets the root route
  
  map.resource :account, :controller => "users"
  map.resources :users
  
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/project.rb
class Project < ActiveRecord::Base
  include Canable::Ables
  
  has_many :project_costs
  belongs_to :business
  belongs_to :user
  has_many :tasks
  has_and_belongs_to_many :users
  
  validates_presence_of :name, :notes, :due_date, :user_id, :business_id
  
  
  def get_cost
    self.tasks.inject(0) { |sum, cost| sum += cost.get_cost }
  end
  
  def to_s
    self.name
  end
  
  def project
    self.task.project
  end
  
  def manager
    self.user
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :require_user
  before_filter :find_users_and_businesses, :only => [:new, :create, :edit, :update]
  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new
  	
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])    
    
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])
	
    respond_to do |format|
      if @project.save
        flash[:notice] = 'Project was successfully created.'
        format.html { redirect_to(@project) }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        flash[:notice] = 'Project was successfully updated.'
        format.html { redirect_to(@project) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  def find_users_and_businesses
    @businesses = Business.find(:all)
	  @users = User.find(:all)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<% form_for(@project) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </p>
  <p>
    <%= f.label :due_date %><br />
    <%= f.date_select :due_date %>
  </p>

  <p>
    <%= f.label :user_id %><br />
    <%= f.collection_select :user_id, @users, :id, :full_name %>
  </p>

  <p>
    <%= f.label :business_id %><br />
    <%= f.collection_select :business_id, @businesses, :id, :name %>
  </p>

	<p><b>Users:</b>
   <% for user in @users %>  
      <div>  
        <%= check_box_tag "project[user_ids][]", user.id, @project.users.include?(user) %>  
        <%= user.full_name %>  
      </div>  
  <% end %>  
	</p>

  <p>
  <% if @project.name then label = 'Update' else label = 'Create' end%>
    <%= f.submit label, :class => "go" %>
  </p>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<% form_for(@project) do |f| %>

	<%= render :partial => 'form' %>

<% end %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
	<th>Name</th>
	<th>Due Date</th>
	<th>Owner</th>
	<th>Business</th>
	<th>Actions</th>
  </tr>

<% @projects.each do |project| %>
  <tr>
	<td><%= project.name %></td>
	<td><%= project.due_date %></td>
	<td><%= project.user %></td>
	<td><%= project.business %></td>
    <td><%= link_to 'Show', project, :class => "awesome small show" %>
	<% if can_update?(project) %>
    <%= link_to 'Edit', edit_project_path(project), :class => "awesome small edit" %>
	<% end %>
	<% if can_destroy?(project) %>
    <%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete, :class => "awesome small destroy" %>
	<% end %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<% form_for(@project) do |f| %>
  <%= f.error_messages %>

	<%= render :partial => 'form' %>

<% end %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p>
  <b>Name:</b>
  <%=h @project.name %>
</p>

<p>
  <b>Description:</b>
  <%=h @project.notes %>
</p>

<p>
  <b>Owner:</b>
  <%=h @project.user %>
</p>

<% if (@project.tasks.size > 0) then %>
<p>
  <b>Tasks:</b>
  <ul>
  <% @project.tasks.each do |task| %>
  	<li><%= link_to task.name, task %></li>
  <% end %>
  </ul>
</p>
<% else %>
<p>
  <b>Tasks:</b>
  There are no tasks in this project.
</p>
<% end %>

<p>
	<b>Total Project Cost:</b>
	<%= @project.get_cost %>
</p>

<p>
  <b>Created:</b>
  <%=h @project.created_at %>
</p>

<% tasks = @project.tasks %>
<% hours = [] %>
<% expenses = [] %>
<% tasks.each do |task|
  hours.concat( HourReport.find(:all, :conditions => {:task_id => task.id, :state => HourReport::Pending } ) )
  expenses.concat( Expense.find(:all, :conditions => {:task_id => task.id, :state => Expense::Pending } ) ) 
    end%>

<% if hours[0] && can_approve?(hours[0]) %>
  <h3>Pending hour reports</h3>
  <table>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Date</th>
      <th>Hours</th>
      <th>State</th>
    </tr>
<% hours.each do |hour| %>
  <tr>
    <td><%=h hour.user %></td>
    <td><%=h hour.name %></td>
    <td><%=h hour.date %></td>
    <td><%=h hour.hours %></td>
    <td><%=h hour.state_to_s %></td>
    <td><%= link_to( 'Show', "../hour_reports/" + hour.id.to_s ) %> |
    <%= link_to( 'Approve', "../hour_reports/approve/" + hour.id.to_s ) %> |
    <%= link_to( 'Reject', "../hour_reports/reject/" + hour.id.to_s )%></td>
  </tr>
<% end %>

</table>
<% end %>

<% if expenses[0] && can_approve?(expenses[0]) %>
  <h3>Pending expenses</h3>
  <table>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Date</th>
      <th>Cost</th>
      <th>State</th>
    </tr>
<% expenses.each do |expense| %>
  <tr>
    <td><%=h expense.user %></td>
    <td><%=h expense.name %></td>
    <td><%=h expense.date %></td>
    <td><%=h expense.cost_to_s %></td>
    <td><%=h expense.state_to_s %></td>
    <td><%= link_to( 'Show', "../expenses/" + expense.id.to_s ) %> |
    <%= link_to( 'Approve', "../expenses/approve/" + expense.id.to_s ) %> |
    <%= link_to( 'Reject', "../expenses/reject/" + expense.id.to_s )%></td>
  </tr>
<% end %>

</table>
<% end %>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>